In [243]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [244]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [245]:
df.tail()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564  926424         M        21.56         22.39          142.00     1479.0   
565  926682         M        20.13         28.25          131.20     1261.0   
566  926954         M        16.60         28.08          108.30      858.1   
567  927241         M        20.60         29.33          140.10     1265.0   
568   92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
564                  0.07115          NaN  
565                  0.06637          NaN  
566                  0.07820          NaN  
567                  0.12400          NaN  
568                  0.07039          NaN  

[5 rows x 33 columns]

In [246]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [247]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [248]:
x_train

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
250        20.94         23.56          138.90     1364.0          0.10070   
420        11.57         19.04           74.20      409.7          0.08546   
119        17.95         20.01          114.20      982.0          0.08402   
368        21.71         17.25          140.90     1546.0          0.09384   
121        18.66         17.12          121.40     1077.0          0.10540   
..           ...           ...             ...        ...              ...   
354        11.14         14.07           71.24      384.6          0.07274   
523        13.71         18.68           88.73      571.0          0.09916   
298        14.26         18.17           91.22      633.1          0.06576   
305        11.60         24.49           74.23      417.2          0.07474   
483        13.70         17.64           87.76      571.1          0.09950   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
250           0.16060         0.27120              0.13100         0.2205   
420           0.07722         0.05485              0.01428         0.2031   
119           0.06722         0.07293              0.05596         0.2129   
368           0.08562         0.11680              0.08465         0.1717   
121           0.11000         0.14570              0.08665         0.1966   
..                ...             ...                  ...            ...   
354           0.06064         0.04505              0.01471         0.1690   
523           0.10700         0.05385              0.03783         0.1714   
298           0.05220         0.02475              0.01374         0.1635   
305           0.05688         0.01974              0.01313         0.1935   
483           0.07957         0.04548              0.03160         0.1732   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
250                 0.05898  ...         25.58          27.00   
420                 0.06267  ...         13.07          26.98   
119                 0.05025  ...         20.58          27.83   
368                 0.05054  ...         30.75          26.44   
121                 0.06213  ...         22.25          24.90   
..                      ...  ...           ...            ...   
354                 0.06083  ...         12.12          15.82   
523                 0.06843  ...         15.11          25.63   
298                 0.05586  ...         16.22          25.26   
305                 0.05878  ...         12.44          31.62   
483                 0.06088  ...         14.96          23.53   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
250           165.30      2010.0           0.12110             0.3172   
420            86.43       520.5           0.12490             0.1937   
119           129.20      1261.0           0.10720             0.1202   
368           199.50      3143.0           0.13630             0.1628   
121           145.40      1549.0           0.15030             0.2291   
..               ...         ...               ...                ...   
354            79.62       453.5           0.08864             0.1256   
523            99.43       701.9           0.14250             0.2566   
298           105.80       819.7           0.09445             0.2167   
305            81.39       476.5           0.09545             0.1361   
483            95.78       686.5           0.11990             0.1346   

     concavity_worst  concave points_worst  symmetry_worst  \
250          0.69910               0.21050          0.3126   
420          0.25600               0.06664          0.3035   
119          0.22490               0.11850          0.4882   
368          0.28610               0.18200          0.2510   
121          0.32720               0.16740          0.2894   
..               ...                   ...             ...   
354          0.12010               0.03922         

In [249]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [250]:
y_train

250    M
420    B
119    M
368    M
121    M
      ..
354    B
523    B
298    B
305    B
483    B
Name: diagnosis, Length: 455, dtype: object

In [251]:
enabler=LabelEncoder()
y_train=enabler.fit_transform(y_train)
y_test=enabler.transform(y_test)

In [252]:
y_train

array([1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,

In [253]:
y_train.shape

(455,)

In [254]:
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [255]:
x_train_tensor=x_train_tensor.to(torch.float32)
x_test_tensor=x_test_tensor.to(torch.float32)
y_train_tensor=y_train_tensor.to(torch.float32)
y_test_tensor=y_test_tensor.to(torch.float32)

In [256]:
y_train_tensor.shape

torch.Size([455])

In [257]:
y_train_tensor.shape

torch.Size([455])

In [258]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,x):
    out=self.linear(x)
    out=self.sigmoid(out)
    return out

In [259]:
model.linear.weight.dtype

torch.float32

In [260]:
model=Model(x_train_tensor.shape[1])

In [261]:
learning_rate=0.01
epochs=100
lossfunc=nn.BCELoss()



In [262]:
for epoch in range(epochs):
  y_pred=model(x_train_tensor)
  loss=lossfunc(y_pred,y_train_tensor.view(-1,1))
  optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()
  print(f'epoch:{epoch},loss:{loss}')

epoch:0,loss:0.9227070808410645
epoch:1,loss:0.8366342186927795
epoch:2,loss:0.7578330636024475
epoch:3,loss:0.6865978240966797
epoch:4,loss:0.6228844523429871
epoch:5,loss:0.56641685962677
epoch:6,loss:0.5167111754417419
epoch:7,loss:0.4729412794113159
epoch:8,loss:0.4343433082103729
epoch:9,loss:0.4003544747829437
epoch:10,loss:0.3704225718975067
epoch:11,loss:0.3440888822078705
epoch:12,loss:0.320900022983551
epoch:13,loss:0.3002917170524597
epoch:14,loss:0.28184106945991516
epoch:15,loss:0.2650894522666931
epoch:16,loss:0.24988283216953278
epoch:17,loss:0.23604635894298553
epoch:18,loss:0.22341831028461456
epoch:19,loss:0.21187178790569305
epoch:20,loss:0.20130841434001923
epoch:21,loss:0.19163952767848969
epoch:22,loss:0.18274587392807007
epoch:23,loss:0.17455846071243286
epoch:24,loss:0.16702570021152496
epoch:25,loss:0.16009356081485748
epoch:26,loss:0.1536971777677536
epoch:27,loss:0.14779849350452423
epoch:28,loss:0.1423536241054535
epoch:29,loss:0.13729088008403778
epoch:30,l

In [263]:
y_pred_test=model(x_test_tensor)
y_pred_test

tensor([[1.8848e-06],
        [4.5480e-03],
        [6.6800e-01],
        [9.4357e-01],
        [1.2206e-01],
        [2.6393e-02],
        [9.0007e-01],
        [2.2368e-05],
        [9.9859e-01],
        [9.9999e-01],
        [2.8052e-04],
        [1.2011e-02],
        [9.9865e-01],
        [3.7668e-05],
        [9.9387e-01],
        [2.7488e-04],
        [1.0000e+00],
        [9.9894e-01],
        [9.6047e-02],
        [9.5779e-06],
        [4.7127e-05],
        [9.9373e-04],
        [5.2877e-04],
        [9.9893e-01],
        [2.1362e-02],
        [1.4570e-05],
        [9.5690e-01],
        [1.3447e-03],
        [2.5508e-05],
        [2.6658e-02],
        [7.2871e-06],
        [1.0000e+00],
        [4.1263e-03],
        [3.6093e-04],
        [9.9840e-01],
        [1.0000e+00],
        [4.2188e-03],
        [9.2260e-06],
        [5.1885e-05],
        [1.0000e+00],
        [3.2200e-03],
        [7.2759e-01],
        [1.6986e-03],
        [7.6767e-05],
        [9.9538e-01],
        [8

In [264]:
y_pred_test_final=(y_pred_test>0.5).float()
y_pred_test_final

tensor([[0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
      

In [267]:
accuracy=(y_pred_test_final==y_test_tensor).float().mean()
accuracy
print(f'Accuracy:{accuracy*100}%')

Accuracy:53.462608337402344%
