In [2]:
import torch
import torch.nn as nn

In [5]:
class mymodel(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out





In [6]:
features=torch.rand(20,5)
model=mymodel(features.shape[1])
model(features)

tensor([[0.5605],
        [0.4440],
        [0.4734],
        [0.3804],
        [0.5373],
        [0.5019],
        [0.4601],
        [0.5470],
        [0.5233],
        [0.5043],
        [0.4947],
        [0.5280],
        [0.5330],
        [0.5524],
        [0.4281],
        [0.5350],
        [0.4957],
        [0.5728],
        [0.5146],
        [0.5347]], grad_fn=<SigmoidBackward0>)

In [14]:
features

tensor([[5.1468e-01, 1.7394e-01, 6.0535e-01, 6.2472e-01, 9.4034e-01],
        [1.7442e-01, 7.8112e-01, 5.0804e-01, 7.0428e-01, 3.6555e-01],
        [6.6333e-01, 7.1089e-01, 4.4167e-01, 6.2200e-01, 3.1512e-01],
        [1.8737e-01, 8.2251e-01, 9.5105e-01, 9.4942e-01, 3.6175e-01],
        [3.9709e-01, 1.9993e-01, 7.9102e-01, 4.9253e-01, 7.7539e-01],
        [4.3078e-01, 6.5542e-01, 6.8814e-01, 6.1414e-01, 8.4010e-01],
        [3.3404e-01, 4.0585e-01, 6.9712e-01, 9.6195e-01, 5.9342e-01],
        [8.2271e-01, 3.9051e-01, 2.5844e-01, 4.1625e-01, 3.7081e-01],
        [2.4566e-01, 3.3476e-01, 7.8030e-01, 3.9423e-01, 6.7975e-01],
        [6.0648e-01, 9.1573e-01, 3.5020e-01, 3.1539e-01, 4.2774e-01],
        [1.4440e-01, 8.0224e-01, 5.5334e-03, 7.0937e-01, 4.9217e-01],
        [7.0030e-01, 6.1012e-01, 4.3334e-01, 6.2305e-01, 7.7786e-01],
        [2.8780e-01, 2.3900e-02, 2.6634e-01, 6.2445e-01, 2.9376e-01],
        [1.8464e-02, 7.5244e-01, 1.0825e-01, 4.4906e-01, 8.9874e-01],
        [1.1250e-01,

In [7]:
model.linear.weight

Parameter containing:
tensor([[ 0.1179, -0.3401, -0.3340, -0.4123,  0.3843]], requires_grad=True)

In [8]:
model.linear.bias

Parameter containing:
tensor([0.3399], requires_grad=True)

In [11]:
!pip install torchinfo


In [12]:
from torchinfo import summary

In [13]:
summary(model,features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
mymodel                                  [20, 1]                   --
├─Linear: 1-1                            [20, 1]                   6
├─Sigmoid: 1-2                           [20, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00