In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print(f"GPU is: {torch.cuda.get_device_name(0)}")
else:
  print("cpu")

GPU is: Tesla T4


TENSORS

In [ ]:
torch.empty(2,3)

tensor([[2.7507e+01, 0.0000e+00, 5.1127e+04],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])

In [ ]:
a=torch.empty(3,3)
type(a)

torch.Tensor

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.rand(3,3)

tensor([[0.7085, 0.6225, 0.1615],
        [0.0688, 0.9639, 0.3586],
        [0.6093, 0.5892, 0.4475]])

In [ ]:
torch.manual_seed(10)
torch.rand(3,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118],
        [0.6938, 0.9693, 0.6178]])

In [ ]:
torch.manual_seed(10)
torch.rand(3,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118],
        [0.6938, 0.9693, 0.6178]])

Same seed provides same value of rand numbers

In [ ]:
torch.manual_seed(20)
torch.rand(3,3)

tensor([[0.5615, 0.1774, 0.8147],
        [0.3295, 0.2319, 0.7832],
        [0.8544, 0.1012, 0.1877]])

In [ ]:
torch.linspace(0,20,10)

tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])

In [ ]:
torch.full((2,3),10)

tensor([[10, 10, 10],
        [10, 10, 10]])

In [ ]:
torch.eye(3,3)#Identity matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

TENSOR SHAPES




In [ ]:
x=torch.empty(5,5)

In [ ]:
x.shape


torch.Size([5, 5])

In [ ]:
x.size

<function Tensor.size>

In [ ]:
x.dtype

torch.float32

In [ ]:
torch.ones_like(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.9414, 0.7402, 0.5991, 0.8456, 0.2241],
        [0.1478, 0.6324, 0.8424, 0.2268, 0.1284],
        [0.5433, 0.1572, 0.1861, 0.5771, 0.8490],
        [0.0099, 0.2720, 0.5121, 0.9844, 0.1236],
        [0.7868, 0.4858, 0.7822, 0.6113, 0.4485]])

In [ ]:
x.to(torch.float32)

tensor([[       nan, 4.4047e-41,        nan, 4.4047e-41, 9.8439e-12],
        [9.8439e-12, 9.8439e-12, 9.8439e-12, 9.8439e-12, 9.8439e-12],
        [9.8439e-12, 9.8439e-12, 9.8439e-12, 9.8439e-12, 9.8439e-12],
        [9.8439e-12, 9.8439e-12, 9.8439e-12, 9.8439e-12, 9.8439e-12],
        [4.3678e+16, 1.1450e-22, 4.3583e-08, 2.3799e+20, 3.9098e+30]])

In [ ]:
x=torch.ones(5,5)

In [ ]:
x.to(torch.float32)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
x+2

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

In [ ]:
x-2

tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])

In [ ]:
x*3

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

In [ ]:
x**2

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
x

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
x-2

tensor([[-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1.]])

In [ ]:
x//2

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
x/2

tensor([[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000, 0.5000, 0.5000]])

In [ ]:
x%1

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
x.add_(9)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])

In [ ]:
torch.round(x)

tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])

In [ ]:
torch.det(x)

tensor(0.)

In [ ]:
y=torch.empty(4,4)

In [ ]:
torch.round(y)

tensor([[       nan, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1644e+12]])

In [ ]:
torch.floor(y)


tensor([[       nan, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 3.1644e+12]])

In [ ]:
z=torch.tensor([1.1,2.3,4.6,5.9])

In [ ]:
torch.floor(z)

tensor([1., 2., 4., 5.])

In [ ]:
torch.ceil(z)

tensor([2., 3., 5., 6.])

In [ ]:
torch.clamp(z,2,3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [ ]:
torch.sum(z)

tensor(13.9000)

In [ ]:
z=torch.rand(3,3)

In [ ]:
torch.sum(z,dim=0)

tensor([1.4492, 0.6628, 1.3842])

In [ ]:
torch.mean(z)

tensor(0.3885)

In [ ]:
torch.min(z)

tensor(0.1581)

In [ ]:
torch.prod(z)

tensor(5.7510e-05)

In [ ]:
torch.std(z)

tensor(0.2287)

In [ ]:
torch.var(z)

tensor(0.0523)

In [ ]:
torch.argmax(z)

tensor(3)

In [ ]:
torch.argmax(z)

tensor(3)

In [ ]:
x=torch.rand(2,3)
x.shape
z.shape

torch.Size([3, 3])

In [ ]:
z.shape

torch.Size([3, 3])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.matmul(x,z)

tensor([[0.7620, 0.3782, 0.8361],
        [0.6507, 0.3774, 0.9920]])

In [ ]:
#.  torch.dot(vect1,vect2)

In [3]:
a=torch.tensor([1,2,3])
b=a
id(a)
id(b)

133188546195152

In [4]:
id(b)

133188546195152

In [5]:
id(a)

133188546195152

In [7]:
b=a.clone()

In [8]:
id(b)

133188546195056