In [30]:
import torch
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
data.tail()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
564  926424         M  ...                  0.07115          NaN
565  926682         M  ...                  0.06637          NaN
566  926954         M  ...                  0.07820          NaN
567  927241         M  ...                  0.12400          NaN
568   92751         B  ...                  0.07039          NaN

[5 rows x 33 columns]

In [6]:
data.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [8]:
data.drop(columns=["id","Unnamed: 32"],inplace=True)

In [33]:
x_train,x_test,y_train,y_test=  train_test_split(data.iloc[:,1:],data.iloc[:,0],test_size=0.2)

In [35]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [36]:
label_encoder=LabelEncoder()
y_train=label_encoder.fit_transform(y_train)
y_test=label_encoder.transform(y_test)

In [68]:
x_train

tensor([[ 0.9783,  1.3065,  1.0290,  ...,  0.9039, -1.2150,  0.5420],
        [-0.8858, -1.0537, -0.8875,  ..., -0.7088,  0.5255, -0.6095],
        [ 0.6304,  0.3455,  0.6409,  ...,  0.6911,  0.3602, -0.0872],
        ...,
        [ 0.1463,  0.9700,  0.0954,  ...,  0.3456, -0.6855, -0.8675],
        [ 0.2738, -0.6155,  0.2962,  ..., -0.1804, -1.1866,  0.1124],
        [ 0.2912,  0.6626,  0.2342,  ...,  0.6093, -0.3548, -0.2743]])

In [64]:
y_test
type(y_test)

torch.Tensor

TypeError: expected np.ndarray (got Tensor)

In [72]:

x_train
x_test


tensor([[ 1.1291, -2.1551,  1.3116,  ...,  2.3430,  2.8624,  2.0236],
        [-0.7785, -2.0486, -0.7748,  ..., -0.3689,  0.2148,  0.0975],
        [-0.6771, -0.2766, -0.7048,  ..., -0.6462, -1.5190, -0.8223],
        ...,
        [ 1.8104,  0.5391,  1.8643,  ...,  2.3908,  4.4610,  1.0797],
        [ 0.2478, -0.1241,  0.2587,  ..., -0.4542, -0.0591,  0.4951],
        [-1.3128, -0.8164, -1.3287,  ..., -0.6366, -0.2178, -0.0998]])

In [78]:
class Model():

  def __init__(self,x):
    self.weight=torch.rand(x.shape[1],1,dtype=torch.float32,requires_grad=True)
    self.bias=torch.rand(1,dtype=torch.float32,requires_grad=True)

  def forward(self,x):
    out=torch.matmul(x,self.weight)+self.bias
    out=torch.sigmoid(out)
    return out

  def lossfunc(self,y_pred,y_train):
    ep=1e-6
    y_pred=torch.clamp(y_pred,ep,1-ep)
    loss = -(y_train * torch.log(y_pred) + (1 - y_train) * torch.log(1 - y_pred)).mean()
    return loss


In [80]:
model=Model(x_train)
epochs=1000
learning_rate=0.01
for epoch in range(epochs):
  y_pred=model.forward(x_train)
  loss=model.lossfunc(y_pred,y_train)
  loss.backward()

  with torch.no_grad():
    model.weight-=learning_rate*(model.weight.grad)
    model.bias-=learning_rate*(model.bias.grad)

  model.weight.grad.zero_()
  model.bias.grad.zero_()

  print(f'epoch:{epoch+1},loss:{loss.item()}')





epoch:1,loss:3.6951868534088135
epoch:2,loss:3.686675786972046
epoch:3,loss:3.6780202388763428
epoch:4,loss:3.668811798095703
epoch:5,loss:3.6599395275115967
epoch:6,loss:3.6507468223571777
epoch:7,loss:3.6413660049438477
epoch:8,loss:3.6323671340942383
epoch:9,loss:3.622788906097412
epoch:10,loss:3.6130943298339844
epoch:11,loss:3.603229284286499
epoch:12,loss:3.5935218334198
epoch:13,loss:3.5832786560058594
epoch:14,loss:3.5731427669525146
epoch:15,loss:3.5625972747802734
epoch:16,loss:3.5525522232055664
epoch:17,loss:3.5421156883239746
epoch:18,loss:3.5316383838653564
epoch:19,loss:3.5211799144744873
epoch:20,loss:3.510655164718628
epoch:21,loss:3.5003697872161865
epoch:22,loss:3.4899163246154785
epoch:23,loss:3.4795117378234863
epoch:24,loss:3.468906879425049
epoch:25,loss:3.458495855331421
epoch:26,loss:3.44816517829895
epoch:27,loss:3.437603235244751
epoch:28,loss:3.4269845485687256
epoch:29,loss:3.4162473678588867
epoch:30,loss:3.4053804874420166
epoch:31,loss:3.3944692611694336

In [81]:
model.weight

tensor([[ 0.2672],
        [-0.0017],
        [ 0.3258],
        [ 0.2361],
        [ 0.0645],
        [-0.1394],
        [ 0.0387],
        [-0.0438],
        [-0.2458],
        [ 0.3501],
        [-0.1252],
        [ 0.0201],
        [-0.2871],
        [ 0.2562],
        [ 0.0682],
        [ 0.1082],
        [ 0.0370],
        [ 0.1053],
        [-0.0943],
        [-0.0542],
        [ 0.2311],
        [ 0.0368],
        [-0.5865],
        [ 0.0249],
        [ 0.0821],
        [ 0.0997],
        [-0.1130],
        [-0.3875],
        [ 0.3318],
        [-0.1793]], requires_grad=True)

In [82]:
y_pred

tensor([[0.2836],
        [0.3903],
        [0.4458],
        [0.4576],
        [0.3947],
        [0.3747],
        [0.4724],
        [0.4891],
        [0.3697],
        [0.4841],
        [0.5979],
        [0.4386],
        [0.4685],
        [0.3603],
        [0.2844],
        [0.3631],
        [0.3302],
        [0.4851],
        [0.5067],
        [0.4206],
        [0.2011],
        [0.4741],
        [0.4680],
        [0.4200],
        [0.4919],
        [0.3560],
        [0.4310],
        [0.3998],
        [0.2952],
        [0.3962],
        [0.4394],
        [0.4092],
        [0.4874],
        [0.4056],
        [0.3797],
        [0.4950],
        [0.6287],
        [0.2935],
        [0.3978],
        [0.3891],
        [0.4810],
        [0.5155],
        [0.3347],
        [0.4150],
        [0.4612],
        [0.4996],
        [0.2998],
        [0.3983],
        [0.6026],
        [0.3927],
        [0.3955],
        [0.4812],
        [0.3975],
        [0.3591],
        [0.3140],
        [0

In [86]:
with torch.no_grad():
  y_pred_test=model.forward(x_test)
  y_pred_label=(y_pred_test>0.5).float()
  print(y_pred_label)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
      

In [88]:
accuracy=(y_pred_label==y_test).float().mean()
print(f'accuracy:{accuracy*100}')

accuracy:59.002769470214844
